
version: 0.2
phases:
    install:
        commands:
            - npm install
    build:
        commands:
            - npm run build
            - cp appspec.yml build/
artifacts:
    base-directory: build
    files:
        - '**/*'
cache:
    paths:
        - node_modules/**/*
